'use client'
import { useEffect, useState } from 'react'
import { CheckCircle2, CircleDollarSign, PackageCheck, Scale, XCircle } from 'lucide-react'

export default function Workbench() {
  const [data,setData]=useState<any>(null), [decision,setDecision]=useState('')
  useEffect(()=>{fetch('/api/procurement?view=workbench').then(r=>r.json()).then(setData)},[])
  function decide(value:string){ const entry={notice:data.case.notice_id,decision:value,at:new Date().toISOString(),actor:'Human approver'}; localStorage.setItem('pec-decisions',JSON.stringify([entry,...JSON.parse(localStorage.getItem('pec-decisions')||'[]')])); setDecision(value) }
  if(!data?.case) return <div className='p-8 text-brand-muted'>Loading approval evidence…</div>
  const c=data.case, inventory=data.inventory.reduce((s:number,r:any)=>s+Number(r.on_hand_qty||0),0), alt=data.alternatives[0]
  return <div className='mx-auto w-full max-w-6xl space-y-6'><div><p className='text-xs font-semibold uppercase tracking-[.24em] text-brand-cornflower'>Human-in-the-loop</p><h1 className='mt-2 text-4xl'>Approval Workbench</h1><p className='mt-2 text-brand-muted'>Review supporting evidence before committing a high-impact recovery action.</p></div>
    {decision&&<div className='rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-900'>Decision recorded: <strong>{decision}</strong>. Audit trail saved.</div>}
    <div className='grid gap-5 lg:grid-cols-[1fr_340px]'><section className='space-y-5'>
      <div className='rounded-2xl border bg-white p-6 shadow-sm'><div className='flex items-start justify-between'><div><span className='rounded-full bg-red-50 px-3 py-1 text-xs font-semibold text-red-700'>{c.severity||'HIGH'} RISK</span><h2 className='mt-4 text-2xl'>{c.notice_id}: {c.notice_type}</h2><p className='mt-1 text-brand-muted'>{c.supplier_name} · {c.item_number}</p></div><Scale className='h-8 w-8 text-brand-purple'/></div><p className='mt-5 rounded-xl bg-slate-50 p-4 text-sm leading-6'>{c.message_body}</p></div>
      <div className='grid gap-4 md:grid-cols-3'>{[[PackageCheck,'Available stock',inventory+' units'],[CircleDollarSign,'Demand shortfall',c.shortfall+' units'],[CheckCircle2,'Alternatives',data.alternatives.length+' found']].map(([Icon,label,value]:any)=><div key={label} className='rounded-2xl border bg-white p-5'><Icon className='h-5 w-5 text-brand-purple'/><p className='mt-3 text-xs uppercase text-brand-muted'>{label}</p><p className='mt-1 text-xl font-semibold'>{value}</p></div>)}</div>
      <div className='rounded-2xl border bg-white p-6'><h3 className='text-xl'>Agent evidence package</h3><div className='mt-4 grid gap-4 md:grid-cols-2'><Evidence title='Alternative sourcing' text={alt?`Supplier ${alt.supplier_id}: ${alt.lead_time_days} days, ${alt.currency||'$'}${alt.price} per unit, MOQ ${alt.moq}.`:'No qualified alternative found.'}/><Evidence title='Inventory reallocation' text={`${data.inventory.length} location records reviewed; ${inventory.toLocaleString()} total units identified.`}/><Evidence title='Contract & penalty' text={`${data.contracts.length} contract(s) and ${data.penalties.length} penalty rule(s) reviewed.`}/><Evidence title='Cost trade-off' text={`Shortfall exposure is ${c.shortfall.toLocaleString()} units. Recommendation balances transfer, expedite cost, and contractual risk.`}/></div></div>
    </section><aside className='h-fit rounded-2xl bg-brand-navy p-6 text-white shadow-lg'><h2 className='text-2xl'>Recommended action</h2><p className='mt-3 text-sm leading-6 text-white/70'>Approve a blended recovery: transfer available stock first, then source or expedite the remaining shortfall. Preserve safety stock for priority orders.</p><div className='my-6 border-t border-white/10'/><p className='text-xs uppercase tracking-wider text-white/50'>Approval required because</p><ul className='mt-3 space-y-2 text-sm'><li>• High-severity disruption</li><li>• Customer demand is at risk</li><li>• Financial trade-off exceeds policy threshold</li></ul><div className='mt-7 grid gap-2'><button onClick={()=>decide('APPROVED')} className='flex items-center justify-center gap-2 rounded-xl bg-emerald-400 px-4 py-3 font-semibold text-brand-navy'><CheckCircle2 className='h-5 w-5'/>Approve recovery</button><button onClick={()=>decide('REJECTED')} className='flex items-center justify-center gap-2 rounded-xl border border-white/20 px-4 py-3 font-semibold'><XCircle className='h-5 w-5'/>Reject / revise</button></div></aside></div>
  </div>
}
function Evidence({title,text}:{title:string,text:string}){return <div className='rounded-xl bg-slate-50 p-4'><p className='font-semibold'>{title}</p><p className='mt-2 text-sm leading-6 text-brand-muted'>{text}</p></div>}
