'use client'
import { useEffect, useState } from 'react'
import { FlaskConical, Save, ShieldCheck } from 'lucide-react'
type Policy={id:string;name:string;description:string;value:number;unit:string;enabled:boolean}
const defaults:Policy[]=[
 {id:'severity',name:'High-risk approval',description:'Require human approval when risk score reaches this level.',value:70,unit:'risk score',enabled:true},
 {id:'cost',name:'Financial authority limit',description:'Escalate recovery plans whose incremental cost exceeds this amount.',value:20000,unit:'USD',enabled:true},
 {id:'stock',name:'Safety-stock protection',description:'Block transfers that leave less than this percentage of safety stock.',value:100,unit:'%',enabled:true},
]
export default function Policies(){const [policies,setPolicies]=useState(defaults),[logs,setLogs]=useState<any[]>([]),[test,setTest]=useState('')
 useEffect(()=>{setPolicies(JSON.parse(localStorage.getItem('pec-policies')||JSON.stringify(defaults)));setLogs(JSON.parse(localStorage.getItem('pec-policy-logs')||'[]'))},[])
 function save(){localStorage.setItem('pec-policies',JSON.stringify(policies));const entry={at:new Date().toISOString(),event:'Policy configuration updated',result:'Active immediately'};const next=[entry,...logs];setLogs(next);localStorage.setItem('pec-policy-logs',JSON.stringify(next))}
 function evaluate(){const hits=[];if(policies[0].enabled&&82>=policies[0].value)hits.push(policies[0].name);if(policies[1].enabled&&25000>=policies[1].value)hits.push(policies[1].name);if(policies[2].enabled&&80<policies[2].value)hits.push(policies[2].name);setTest(hits.length?`DN-5000 routes to HUMAN APPROVAL. Triggered: ${hits.join(', ')}.`:'DN-5000 qualifies for automatic execution.')}
 return <div className='mx-auto w-full max-w-5xl space-y-6'><div className='flex items-end justify-between'><div><p className='text-xs font-semibold uppercase tracking-[.24em] text-brand-cornflower'>Governance</p><h1 className='mt-2 text-4xl'>Editable AI Policies</h1><p className='mt-2 text-brand-muted'>Business users can change routing behavior without code.</p></div><button onClick={save} className='flex items-center gap-2 rounded-xl bg-brand-navy px-5 py-3 text-sm font-semibold text-white'><Save className='h-4 w-4'/>Save policies</button></div>
 <div className='grid gap-4'>{policies.map((p,i)=><div key={p.id} className='grid items-center gap-5 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-[1fr_180px_100px]'><div className='flex gap-4'><div className='rounded-xl bg-blue-50 p-3'><ShieldCheck className='h-5 w-5 text-blue-600'/></div><div><h2 className='text-lg'>{p.name}</h2><p className='mt-1 text-sm text-brand-muted'>{p.description}</p></div></div><label className='flex items-center gap-2 rounded-xl border px-3 py-2'><input type='number' value={p.value} onChange={e=>setPolicies(policies.map((x,j)=>j===i?{...x,value:Number(e.target.value)}:x))} className='w-full bg-transparent font-semibold outline-none'/><span className='text-xs text-brand-muted'>{p.unit}</span></label><button onClick={()=>setPolicies(policies.map((x,j)=>j===i?{...x,enabled:!x.enabled}:x))} className={`rounded-full px-3 py-2 text-xs font-semibold ${p.enabled?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{p.enabled?'ACTIVE':'OFF'}</button></div>)}</div>
 <div className='rounded-2xl bg-brand-navy p-6 text-white'><div className='flex items-center gap-3'><FlaskConical className='h-5 w-5 text-brand-cornflower'/><h2 className='text-xl'>Policy evaluation sandbox</h2></div><p className='mt-2 text-sm text-white/60'>Test context: risk 82, incremental cost $25,000, safety stock retained 80%.</p><button onClick={evaluate} className='mt-4 rounded-xl bg-white px-4 py-2 text-sm font-semibold text-brand-navy'>Evaluate DN-5000</button>{test&&<p className='mt-4 rounded-xl bg-white/10 p-4 text-sm'>{test}</p>}</div>
 <div className='rounded-2xl border bg-white p-5'><h2 className='text-xl'>Evaluation log</h2>{logs.length?logs.slice(0,5).map((l,i)=><div key={i} className='mt-3 flex justify-between border-t pt-3 text-sm'><span>{l.event} · {l.result}</span><span className='text-brand-muted'>{new Date(l.at).toLocaleString()}</span></div>):<p className='mt-3 text-sm text-brand-muted'>Save a policy change to create the first audit event.</p>}</div></div>}
